volumes:
  mariadb-data:
  postgresql-data:

networks:
  dev:
    driver: bridge

services:
  # ASP.NET Core application
  account_service:
    container_name: account-service
    build:
      context: .
      dockerfile: ./AccountService/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - auth_service
      - postgresql_db
    environment:
      ConnectionStrings__account-service-db: "Database=account_service_db;Server=postgresql_db;Port=5432;User Id = postgres;Password=nigPostgres_Pas5432;Include Error Detail=true;Pooling=true"
      ConnectionStrings__hangfire-db: "Database=hangfire_db;Server=postgresql_db;Port=5432;User Id = postgres;Password=nigPostgres_Pas5432;Include Error Detail=true;Pooling=true"
      Keycloak__MetadataAddress: "http://auth_service:8080/realms/main_realm-realm/.well-known/openid-configuration"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORTS: 80
    networks:
      - dev
  
  # Postgresql Database
  postgresql_db:
    image: postgres:17.2
    container_name: postgresql
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: account_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nigPostgres_Pas5432
    networks:
      - dev
  
  auth_service:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.2.0
    command:
      - start-dev
#      - "-Dkeycloak.migration.action=import"
#      - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
#      - "-Dkeycloak.migration.provider=singleFile"
#      - "-Dkeycloak.migration.file=/opt/keycloak/data/import/main_realm-realm.json"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT_LOG_LEVEL: DEBUG
      KC_DB: "mariadb"
      KC_DB_USERNAME: "admin"
      KC_DB_PASSWORD: "admin"
      KC_DB_URL: jdbc:mariadb://mariadb:3306/keycloak?characterEncoding=UTF-8
    ports:
      - "8080:8080"
#    volumes:
#      - ./.keycloak-config:/opt/keycloak/data/import:Z
    networks:
      - dev
    depends_on:
      - mariadb
    
    # Keycloak database
  mariadb:
    image: mariadb:11.4.7
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_DATABASE: keycloak
      MARIADB_ROOT_PASSWORD: admin
    healthcheck:
      test: [ "CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 3s
      timeout: 3s
      retries: 20
#    volumes:
#      - mariadb-data:/var/lib/mysql
    networks:
      - dev