name: init

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:latest
    strategy:
      matrix:
        dotnet-version: ['9.0.x']
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore

      - name: Test with dotnet
        run: dotnet test --no-restore --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"

      - name: Upload dotnet test results
        if: ${{ always() }}  # Always run even if previous step fails
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-results-${{ matrix.dotnet-version }}
          path: TestResults-${{ matrix.dotnet-version }}
